services:
  rate-my:
    build: .
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT-8080}:8080"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - ./ratings.log:/app/ratings.log
      - ./config/redis.yml:/app/config/redis.yml:ro
    restart: on-failure:10
